# Configuración de Ruff para Django
target-version = "py313"
line-length = 88

[lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "DJ", # django
    "UP", # pyupgrade
]
ignore = []

[lint.per-file-ignores]
"*/migrations/*.py" = ["E501"]  # Ignorar líneas largas en migraciones

[lint.isort]
known-first-party = ["config"]
